### PR TITLE
Milestone Award Expansion

### PR DESCRIPTION
**Pull request by maserion**
1st set of Milestones and Awards
Milestones - Producer, Philantropist, Fundraiser, Sponsor, Researcher
Awards - Administrator, Investor, Mogul, Construct, Traveller

Code, test and icon for each Milestone/Award done
Image size reduced by using indexed colour mode
Chimera case considered in tests
Base for next part done
image

### CODE REVIEW

**Comment by kberg** [comment]
Sorry, I was not clear enough. This is still too much code to review at once. Here's what i meant:

1. The code and tests for 10 awards and milestones. Ideally those awards and milestones are self-contained and do not have to touch other pieces of the system. Don't include the icons. Those can come later.
2. An update to AwardName and Milestone name to include them.

Don't change any visualization stuff, or change to `Awards` or `Milestones`. They're not being included yet. The change to `Player` shouldn't be there, either.

That means the feature is not generally available. It's just adding the code without disrupting the rest of the app, so that we can include everything safely, in pieces.

Sorry. I recall saying a few times that this should be reviewed in small pieces. This is what I meant.

I hope this helps. Let me know if you have any questions.

**Comment by kberg** [comment]
@maserion how are you doing? Would you like a little help?

**Comment by kberg** [comment]
I wrote this one example for you: https://github.com/terraforming-mars/terraforming-mars/pull/7069

That's just one, but it shows what I mean. This code and test can be reviewed in isolation. it's much easier for me to understand.

**Comment by maserion** [comment]
> I wrote this one example for you: #7069
> 
> That's just one, but it shows what I mean. This code and test can be reviewed in isolation. it's much easier for me to understand.

I prepared PR in requested format - 5x Milestones + tests, 5x Awards + tests, Milestone + Award Names, compatibilities file

**Comment by kberg** [comment]
I think it's OK to close this one. I might be wrong, and let me know if I am. But it reduces the list of pull requests.

**Pull request closed without merging**
