### PR TITLE
New corps

### PR DESCRIPTION
**Pull request by justin-dupre**

### CODE REVIEW

**Comment by kberg** [comment]
What happened?

**Comment by justin-dupre** [comment]
Sorry, I meant to open this against a fork to play test some new corps but opened it here by accident.

**Comment by kberg** [comment]
Sure thing. In the meantime OutOfThisWorld will count more than once. Do
you have a rule about this?

**Comment by kberg** [comment]
Oh, sorry, no, I omitted a specific case: wild tags already played will
count for each tag.

**Pull request closed without merging**
