### PR TITLE
Simon's CSS tweaks

### PR DESCRIPTION
**Pull request by kberg**

### CODE REVIEW

**Review by alrusdi — APPROVED** [review]

**Comment by kberg** [comment]
@ssimeonoff on the whole this is a nice improvement! I have two comments before merging:

1. The three moon global parmeter icons also need to grow. I could look at this afterwards.
2. This makes things a little more difficult if we want to move these to the top of the card, on the same level as the tags. What are your thoughts about the requirements going there eventually?

**Comment by kberg** [comment]
image

**Comment by kberg** [comment]
I fixed the Moon global parameters:

image

**Comment by kberg** [comment]
I spoke privately with @ssimeonoff and he convinced me it's not worth trying to cram the requirements up top. :sob:

**Pull request merged**
