### PR TITLE
Fixed some missing translations

### PR DESCRIPTION
**Pull request by ligvigfui**

### CODE REVIEW

**Comment by kberg** [comment]
Hi. Thanks for this PR. However you're probably going to need to use a clean branch, which also means pulling from origin/main. I realize that might not be obvious if you are new to git, but I can't help more than that.

**Comment by kberg** [comment]
Hi @ligvigfui, I'd be happy to submit this PR, but as mentioned, it has some merge issues. Are you going to be able to work on that?

**Comment by ligvigfui** [comment]
Ok I'll try to merge things and submit a new PR after.

**Comment by ligvigfui** [comment]
Is it better now?
Or is the new PR necessary?

**Review by kberg — APPROVED** [review]

**Comment by kberg** [comment]
Thanks for this!

**Pull request merged**
