### PR TITLE
Update descriptions of cards with Clone tags.

### PR DESCRIPTION
**Pull request by kberg**

### CODE REVIEW

**Comment by kberg** [comment]
image

**Comment by d-little** [comment]
I'd really rather this specific use the number 3, something like:

`"(Choose a planetary track. This card counts as a card with a tag of the chosen planet. Raise the planetary track 3 total steps.)"`

**Comment by kberg** [comment]
The text on all clone tag cards are inconsistent:

> Crew Training: (Choose a planet tag. This card counts as having 2 of that tag. Raise the planetary influence track accordingly. Gain 2 TR.)
> 
> Lobby Halls: (Increase your M€ production 2 steps. Place 1 delegate from reserve in any party.)
> 
> Kickstarter: (Choose a planetary track and raise it 3 steps. This card counts as a card with a tag of the chosen planet.)


1. Lobby Halls requires one clone tag icon (with the pathfinder track) and some text.
2. Resolve "planet" tag vs "planetary tag"

Suggesting:

> Crew Training: (Choose a planet tag. This card counts as having 2 of that tag. Raise the according planetary track 2 steps. Gain 2 TR.)
> 
> Lobby Halls: (Increase your M€ production 2 steps. Place 1 delegate from reserve in any party. Choose a planet tag. This card counts as having 1 of that tag. Raise the according planetary track 1 step.)
> 
> Kickstarter: (Choose a planet tag. This card counts as having 1 of that tag. Raise the according planetary track 3 steps.)

**Comment by kberg** [comment]
Actually, replace "according" with "corresponding"

**Comment by d-little** [comment]
Do the Clone Tags count as their relevant planets while being played, or only after being 'resolved' into play?

ie: Will a clone tag of Jovian trigger Ringcom?

image

I ask because that can influence the wording.  If they enter _as_ Jovian tags, that tag itself will indeed increase the Jovian Planetary Tracker.  But if they enter as 'Clone Tag', and _then_ get resolved, they wouldnt...

I still like the idea of being very specific about the Total number of steps increased:

    Crew Training: (Choose a planet tag. This card counts as having 2 of that tag. Raise the corresponding planetary track 2 steps in total.  Gain 2 TR.)

    Lobby Halls: (Increase your M€ production 2 steps. Place 1 delegate from reserve in any party. Choose a planet tag. This card counts as having 1 of that tag. Raise the corresponding planetary track 1 step in total.)

    Kickstarter: (Choose a planet tag. This card counts as having 1 of that tag. Raise the corresponding planetary track 3 steps in total.)


I considered '3 Total steps' but there's even confusion there, _someone_ will think that you can do partial-steps because of that ;)

**Comment by kberg** [comment]
> Do the Clone Tags count as their relevant planets while being played, or only after being 'resolved' into play?
> 
> ie: Will a clone tag of Jovian trigger Ringcom?
Yes, it will.

**Comment by d-little** [comment]
Looks fine to me, at this point (but I also thought the original was clear!)

**Review by d-little — APPROVED** [review]

**Pull request merged**
