### PR TITLE
Remove Corporations Draft.

### PR DESCRIPTION
**Pull request by kberg**

### CODE REVIEW

**Comment by morazow** [comment]
Hello @kberg,

Thanks for working on open-source version of this amazing game!

I was wondering why corporation draft option is removed. Is there plan to add or improve it?

**Comment by kberg** [comment]
> Hello @kberg,
> 
> Thanks for working on open-source version of this amazing game!
> 
> I was wondering why corporation draft option is removed. Is there plan to add or improve it?

See if https://github.com/terraforming-mars/terraforming-mars/discussions/5597#discussioncomment-5626054 answers your question.

**Comment by morazow** [comment]
Thanks @kberg, yes it does! I also learned there is branch for corporation draft (which we could host separately).

**Comment by kberg** [comment]
You can. It won't contain any future changes.

**Pull request merged**
