### PR TITLE
fixing some German Moon translations

### PR DESCRIPTION
**Pull request by pczyk**
found missing cards in the translation and aligned on renaming some cards together with Borbarad

### CODE REVIEW

**Comment by kberg** [comment]
@Borbarad2 any thoughts?

**Comment by Borbarad2** [comment]
Approved by Borbarad

**Comment by mfmetro** [comment]
Alright, I'm going to add another commit on top.

**Comment by pczyk** [comment]
Alright, I'm going to add another commit on top.

**Pull request merged**
