### PR TITLE
Add a bug reporting widget.

### PR DESCRIPTION
**Pull request by kberg**
To get useful game parameters will require some more wiring, but instead
of wiring game state through things like the prefernces icon I'd rather
use a Vue-standard global state solution. Or instead of hosting the
bug reporting widget inside the preferences widget, to pass a message.

### CODE REVIEW

**Comment by kberg** [comment]
image
image

**Comment by Argeento** [comment]
In gh you can [create an issue from URL query](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue#creating-an-issue-from-a-url-query)

https://github.com/terraforming-mars/terraforming-mars/issues/new?title=hello&body=you%20can%20pass%20game%20config%20here

**Comment by kberg** [comment]
> In gh you can [create an issue from URL query](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue#creating-an-issue-from-a-url-query)
> 
> https://github.com/terraforming-mars/terraforming-mars/issues/new?title=hello&body=you%20can%20pass%20game%20config%20here

Yes, I'm slightly nervous about exceeding URL length, and will investigave whether parameteres can be passed via POST. This I know works, at least.

**Comment by Argeento** [comment]
> Yes, I'm slightly nervous about exceeding URL length, and will investigave whether parameteres can be passed via POST. This I know works, at least.

I think in our scenario this is a quite safety solution. I've once created [that long issue](https://github.com/prisma/prisma/issues/7750) via query url (from node console!)

**Review by bafolts — APPROVED** [review]

**Comment by kberg** [comment]
Fixes #2760

**Pull request merged**
