### PR TITLE
issue-5183 fix planetary track increase log message translation

### PR DESCRIPTION
**Pull request by alrusdi**

### CODE REVIEW

**Comment by Borbarad2** [comment]
Thank you very much. 
Looking forward to see that.

**Review by kberg — APPROVED** [review]
Thanks. While I think the first version is slightly easier to read, this is appropriate.

**Comment by kberg** [comment]
@alrusdi is #5183 completely fixed?

**Comment by alrusdi** [comment]
I hope so :-)

**Pull request merged**
