### PR TITLE
Fix bug in Greenhouses and Energy Saving.

### PR DESCRIPTION
**Pull request by kberg**

### CODE REVIEW

**Review by nwai90 — APPROVED** [review]

**Comment by kberg** [comment]
This was a regression probably introduced when I centralized city counting. More tests = better.

**Comment by kevintchan** [comment]
I think ImmigrationShuttles has the same regression

**Comment by kberg** [comment]
That was fixed and deployed in the last release.

**Comment by kevintchan** [comment]
sorry thanks!

**Comment by kberg** [comment]
No no, thank _you._

**Pull request merged**
