### PR TITLE
Fix: draft save behaviour + in memory database saving

### PR DESCRIPTION
**Pull request by eratchia**
This is where tinkering with #6839 led me. I'm not completely sure of this solution yet so I'm opening it as a draft PR.

This change makes it so that the game is always saved after draft cards are dealt. That should mean that both:
1. Previous "hack" that fixed the behavior of #6810 isn't needed because when the game saves after dealing the cards players needToDraft properties are properly saved.
2. #6839 no longer occurs because partial information that lead to a bad restore isn't saved.

This change additionally fixes a problem with InMemoryDatabase which would freeze on saving a game with a higher lastSaveId because it would use push() which adds no new elements.

### CODE REVIEW

**Comment by kberg** [comment]
Thanks. I'll spend time on this now, and reference this while debugging.

**Comment by kberg** [comment]
@eratchia thank you! The eventual fix is very similar to yours, mostly only structurally different, and includes a test. Do you still want the inmemory database change? I'd be happy to incorporate it.

**Comment by kberg** [comment]
If you want to keep the IMD fix, I'll be happy to reopen this PR or accept a new one.

**Comment by eratchia** [comment]
@kberg Nice! 

The in-memory database change isn't super important as it is in test but it is very annoying to find while debugging. I think fixing it in a similar way could save someone time at some point.

**Pull request closed without merging**
