### PR TITLE
update spanish translations

### PR DESCRIPTION
**Pull request by analizl**

### CODE REVIEW

**Review by kberg — APPROVED** [review]
Thank you! This is great.

**Comment by analizl** [comment]
I just learned how to play the game and I was so excited to find out this web app and this community, I'll continue to upload Spanish translations :)

**Comment by kberg** [comment]
Should I wait a day or two to merge this?

**Comment by analizl** [comment]
It's ok you can merge it, I'll upload another PR

**Comment by kberg** [comment]
This is perfect, thanks!

**Pull request merged**
