### PR TITLE
German localisation overhaul

### PR DESCRIPTION
**Pull request by pczyk**
Hello everyone!

I've been playing terraforming-mars a lot lately and would like to contribute to the project. I've started an overhaul of the German localisation based on the latest Korean file structure, added a lot of missing translations, corrected typos and streamlined some texts. It's still missing the Turmoil and Mood cards but as far as I can tell, they haven't been in the current localisation anyway, so you're not missing out on something. I'm going to work on these ones next.

Thank you for putting so much work into this great board game adaptation!

Cheers,
Martin

### CODE REVIEW

**Comment by kberg** [comment]
This is really terrific. It looks like you've restructured all the files perhaps? Are there lots of duplicates now?

**Comment by pczyk** [comment]
Thanks! Yes, so in the original localisation, the `cards.json` was huge, ~1.4k lines. What I did was taking the freshly added Korean translation (which had a nice structure) and replaced the Korean with existing German translation key by key. Also, I added translation where there was no German yet, e.g. basically everything in `log_messages.json` and a lot more, including cards.

Thank you for pointing out the duplicates issue - I forgot to remove the `cards.json` which is replaced by several expansion-specific files like `colonies_cards.json`. I'm going to correct that.

**Comment by pczyk** [comment]
Alright, after removing the outdated `cards.json` there are still 150+ duplicate keys, probably because they have already been there in the Korean translation. Of course, I'm going to remove them. Stay tuned.

**Comment by kberg** [comment]
I'm going to approve and merge this. Someone is very interested in handling The Moon translations. Are you OK if he does that or were you going to do them?

**Comment by kberg** [comment]
Are you on Discord? Can you DM me?

**Comment by pczyk** [comment]
I don't have access to my Discord account right now, but sure, go ahead and merge it. Sure, I'm fine with somebody else translating The Moon. I can focus on the remaining duplicates and Turmoil then.

**Review by kberg — APPROVED** [review]

**Comment by kberg** [comment]
OK. Thank you!

**Comment by Borbarad2** [comment]
Thank you for the good and basic work, finally this app/game got an (nearly) complete german translation. Thanks to you @Martin.

**Comment by Borbarad2** [comment]
Currently I am working right now on the translation for the moon an pathfinder edition.
Moon is already finished and pahfinder is mostly done. 

I think the best way to communicate each other, @Martin, would be via discord. 

I have translated close/fix to the official German published Version (Schwerkraft Verlag)(I did a lot of research with the German cards how they did the translation and phrasing). I translate mostly consistent to that German Version, and took the same Wording wherever i can. Due to that consistency I would like to improve your German translation without blaming or condemning your wonderful (pre-)work and make it even better: I want to put more consistency in it. (I am a game lector and pay attention/take care of good quality/consistency), and by the way i would put all the missing parts, which could happen because it was not in the (Korean?)-template, maybe we should/need to add here something. 
I am not an developer oder code writer, so i need your teamwork with me to complete and make a perfect german translation. 

Cheers,
Christian

**Comment by pczyk** [comment]
Hey Christian,

I don't own all of the expansions so I don't know the "official" translation so I think it's awesome that you want to streamline the translation. And yes, while being the latest translation, Korean was not complete. I just realized that again when translating Turmoil. A lot of keys were missing.
Another observation that might be helpful for your translation work: Sometimes, there was a German translation but it could not be displayed in-game because its key was slightly different so the game couldn't match it with the card text or name.

Let's connect on Discord then :)

Thanks,
Martin

**Pull request merged**
