### PR TITLE
CEO CreateGameForm :: select starting card count

### PR DESCRIPTION
**Pull request by d-little**
Allow players to choose how many CEOs they'd like to be dealt.

`startingCeos` has been added to all the GameOption locations where `startingCorporations` lives

My playgroup has been using 4 instead of the default 3, sometimes its more interesting.

Output display:

image

image

### CODE REVIEW

**Comment by d-little** [comment]
I forgot, I also modified 

`src/common/game/NewGameConfig.ts`'s `twoCorpsVariant: boolean;`

(it previously ended in a comma?  Nothing seemed to care, but updating it to be in line with the rest of the file)

**Comment by kberg** [comment]
I'd argue this belongs in Options: 
image

**Comment by d-little** [comment]
I dont hate moving it, but we probably need to move the two Moon options over.

I propose adding in the expansion icon though:
image

Just to make it a little more obvious that it's tied to CEOs.

If this looks good we can repeat for all of the other Game Options

**Comment by kberg** [comment]
> I dont hate moving it, but we probably need to move the two Moon options over.
> 
> I propose adding in the expansion icon though: image
> 
> Just to make it a little more obvious that it's tied to CEOs.
> 
> If this looks good we can repeat for all of the other Game Options

Sure. And after thinking, I think your first option was more than acceptable.

**Review by kberg — APPROVED** [review]
There's a pending comment which I cannot find. But it'll appear momentarily, I guess.

**Pull request merged**
