### PR TITLE
Adding support for using multiple font files

### PR DESCRIPTION
**Pull request by tltneon**
Splitted from #5640

Added ability to use multiple font files for different languages
image image

And also edit CSS rules that sets name exactly at the middle of screen.

image

### CODE REVIEW

**Comment by kberg** [comment]
Just a couple of questions. This looks great. Where did the ttf files come from? I would like to indicate their source, particularly to ensure they're open source. Otherwise this looks good to go!

**Comment by tltneon** [comment]
Polish ttf file was taken from [#4276#issuecomment-1305351245](https://github.com/terraforming-mars/terraforming-mars/issues/4276#issuecomment-1305351245)
And Russian ttf from https://fonts-online.ru/fonts/prototype-rus-daymarius has free for personal and non-commertial use license

**Comment by kberg** [comment]
Fixes #4276

**Comment by kberg** [comment]
I wanted to point out that this PR isn't merged @tltneon because I added a PR to **your** repo. Can you review and merge that one in, please?

**Comment by tltneon** [comment]
Oh, I didn't know that I need to accept PR.
Done.

**Review by kberg — APPROVED** [review]

**Review by kberg — APPROVED** [review]

**Pull request merged**
