### PR TITLE
CEO Buck

### PR DESCRIPTION
**Pull request by d-little**
### Buck

image

@nwai90 added this recently, figured I'd bring it over almost entirely as-is because I _really_ like the idea :)

### CODE REVIEW

**Comment by kberg** [comment]
Buck brings up an issue: https://github.com/terraforming-mars/terraforming-mars/issues/4929 which addresses the issue of making cards replayable if they place special tiles.

This includes Bio-Fertilizer Facility, Capital, Commercial District, Great Dam, Luna Mining Hub, Luna Train Station, Mare Imbrium Mine, Mare Nectaris Mine, Mare Serenatis Mine, Mining Area, Mohole Area, Natural Preserve, New Venice, Noctis City, Nuclear Zone, Ocean City, Ocean Farm, Solar Farm, and Wetlands.

There are at least four of those cards that are specifically tricky, that they place a tile in a very specific spot.

(Actually, this excludes all the tiles that place space colonies, like Stanford Torus, not to mention that Stanford Torus played twice, by the rules, is  kinda tricly.)

**Comment by d-little** [comment]
> Buck brings up an issue: #4929 which addresses the issue of making cards replayable if they place special tiles.
> 
> This includes Bio-Fertilizer Facility, Capital, Commercial District, Great Dam, Luna Mining Hub, Luna Train Station, Mare Imbrium Mine, Mare Nectaris Mine, Mare Serenatis Mine, Mining Area, Mohole Area, Natural Preserve, New Venice, Noctis City, Nuclear Zone, Ocean City, Ocean Farm, Solar Farm, and Wetlands.
> 
> There are at least four of those cards that are specifically tricky, that they place a tile in a very specific spot.
> 
> (Actually, this excludes all the tiles that place space colonies, like Stanford Torus, not to mention that Stanford Torus played twice, by the rules, is kinda tricly.)

Maybe we need to expand the scope, exlude _any_ card that places a special tile?  Or even any tile?  Seems bad for cars that place regular forests and oceans

@nwai90 any thoughts?

**Comment by nwai90** [comment]
> > Buck brings up an issue: #4929 which addresses the issue of making cards replayable if they place special tiles.
> > This includes Bio-Fertilizer Facility, Capital, Commercial District, Great Dam, Luna Mining Hub, Luna Train Station, Mare Imbrium Mine, Mare Nectaris Mine, Mare Serenatis Mine, Mining Area, Mohole Area, Natural Preserve, New Venice, Noctis City, Nuclear Zone, Ocean City, Ocean Farm, Solar Farm, and Wetlands.
> > There are at least four of those cards that are specifically tricky, that they place a tile in a very specific spot.
> > (Actually, this excludes all the tiles that place space colonies, like Stanford Torus, not to mention that Stanford Torus played twice, by the rules, is kinda tricly.)
> 
> Maybe we need to expand the scope, exlude _any_ card that places a special tile? Or even any tile? Seems bad for cars that place regular forests and oceans
> 
> @nwai90 any thoughts?

Perhaps it needs to expand to exclude cards that place tiles on reserved areas (e.g. space cities), and cards that place greenery tiles on ocean spaces

**Comment by kberg** [comment]
Sorry, if I wasn't clear, there's already a ruling: #4929 was resolved with the decision that cards that place special tiles _can_ be replayed, and I'd like this to be consistent. The issue was resolved with a comment in the card description that makes this explicit.

image

And I think these should be the same. However, this makes it complicated for Noctis City, Stanford Torus, et cetera. And now that I've had a minute to consider it, here's what I think about those:

If you're playing with CEOs, then you're not a beginner. If you pull Noctis City back it's because you know what you are doing. Noctis City should not be replayable since you can't do everything on the card, and so the only think you can do with it is sell the patent. *But* it also  means that all those cards  (the ones above, and also Stratopolis, Ganymede Colony, etc) need to be changed so their canPlay doesn't let them get played if the tile is already there.

But it's not like this kind of problem is isolated to this condition. After all, it's a waste to pull back Archebacteria if the temperature is too high:

image

And just to think about the future: if you have two CEOs, Faraday is also not prepared for this.

**Comment by d-little** [comment]
> Noctis City 

I'm pretty sure if the Noctis City space is is not available the game lets you place a city anywhere.

Looking at the code, this seems to be the way it's implemented:
```ts
  public override bespokeCanPlay(player: Player): boolean {
    if (player.game.board.getNoctisCitySpaceId !== undefined) {
      return true;
    } else {
      return player.game.board.getAvailableSpacesForCity(player).length > 0;
    }
  }
  public override bespokePlay(player: Player) {
    const noctisCitySpaceId = player.game.board.getNoctisCitySpaceId();
    if (noctisCitySpaceId !== undefined) {
      const space = player.game.board.getSpace(noctisCitySpaceId);
      player.game.addCityTile(player, space);
      return undefined;
    }
    return new SelectSpace('Select space for Noctis city', player.game.board.getAvailableSpacesForCity(player), (space: ISpace) => {
      player.game.addCityTile(player, space);
      return undefined;
    });
  }

```

`Stratopolis` does not behave this way, it's always assumed the Space tile is available.  Is there a possibility for a blanket ruling?  If a card would place a city tile on a Space location, but that location is not available (missing, occupied, or any other reason), instead you may place the city per normal city placement rules?

**Comment by kberg** [comment]
> > Noctis City
> 
> I'm pretty sure if the Noctis City space is is not available the game lets you place a city anywhere.

Only on maps that don't have a Noctis City space on their maps.

`getNoctisCitySpaceId()` returns the space ID for the map. Tharsis has one. Hellas does not. The rules for Hellas are that NC allows you to place a city anywhere. So, playing Noctis City on Tharsis a second time will still try to place the tile on the reserved space. Which it cannot because a city is already there.

> Looking at the code, this seems to be the way it's implemented:

By the way, small bug. Hah!

> 
> ```ts
>   public override bespokeCanPlay(player: Player): boolean {
>     if (player.game.board.getNoctisCitySpaceId !== undefined) {
      ^--- bug. This should be getNoctisCitySpaceId().
>       return true;
>     } else {
>       return player.game.board.getAvailableSpacesForCity(player).length > 0;
>     }
>   }
>   public override bespokePlay(player: Player) {
>     const noctisCitySpaceId = player.game.board.getNoctisCitySpaceId();
>     if (noctisCitySpaceId !== undefined) {
>       const space = player.game.board.getSpace(noctisCitySpaceId);
>       player.game.addCityTile(player, space);
>       return undefined;
>     }
>     return new SelectSpace('Select space for Noctis city', player.game.board.getAvailableSpacesForCity(player), (space: ISpace) => {
>       player.game.addCityTile(player, space);
>       return undefined;
>     });
>   }
> ```
> 
> `Stratopolis` does not behave this way, it's always assumed the Space tile is available. Is there a possibility for a blanket ruling? If a card would place a city tile on a Space location, but that location is not available (missing, occupied, or any other reason), instead you may place the city per normal city placement rules?

Replaying Stanford Torus means getting a city on the map for 12MC. Dawn City gives you a city + Titanium production for 15. Great for greenery bonuses. Also, I don't think it makes sense for a space tag card to be used to place a city on the surface, paying with Titanium.

**Comment by kberg** [comment]
What's the current status?

**Comment by d-little** [comment]
Closing this, will likely reopen when I revisit Buck

**Pull request closed without merging**
