### PR TITLE
Update .dockerignore

### LINKED ISSUE #4015: Docker build broken in recent commit
This commit https://github.com/terraforming-mars/terraforming-mars/commit/ff760848a78490b0b72b006fdde92e1e73e7c4ae has broken the docker build:

log1

This results in missing versioning info on the site:

log2

Can the be reverted? @kberg @jholm117

### PR DESCRIPTION
**Pull request by jholm117**
Should fix #4015

### CODE REVIEW

**Comment by jholm117** [comment]
I'll add it would be nice if that error had failed the CI validation

**Review by kberg — APPROVED** [review]

**Comment by kberg** [comment]
Thank you!

**Comment by kberg** [comment]
> I'll add it would be nice if that error had failed the CI validation

It would be but I'm reluctant to take that on since we don't support Docker explicitly. Nobody currently maintaining this project knows enough to do anything, and I'm mostly the guy right now.

**Comment by kberg** [comment]
> > I'll add it would be nice if that error had failed the CI validation
> 
> It would be but I'm reluctant to take that on since we don't support Docker explicitly. Nobody currently maintaining this project knows enough to do anything, and I'm mostly the guy right now.

My recommendation is to fork this repo with a single change that enforces the docker test.

**Pull request merged**
