### PR TITLE
Remove checkbox from card selection, replace with subtle brightness shift.

### LINKED ISSUE #3211: Remove the orange bar - revert to the orange border
In cases where only one card is available to select, the orange bar occludes the text.

image

### PR DESCRIPTION
**Pull request by kberg**
Fixes #3211

Before
image
After
image

### CODE REVIEW

**Comment by nwai90** [comment]
@kberg I found some issues with this change, as the same UI is shared for colony and turmoil party selection, so the checkmarks are removed for those as well. We might need to define new classes for it so that we preserve the visual indicator for at least the turmoil parties:

Screenshot 2022-04-24 at 12 10 44 PM

Screenshot 2022-04-24 at 12 10 54 PM

**Comment by kberg** [comment]
Ooh, thank you. Yes, that makes sense.

**Comment by pauliimmonen** [comment]
I wonder if this could be the more subtle approach? I kept the checkbox for distinguishability and as small as possible above the card. Tho I had to make few pixels room between card rows. Too small checkbox would be behind the corporation tag and it looked very inconvenient in front of it. Colonies and turmoil checkboxes as they were.

project_cards
standard

**Comment by kberg** [comment]
> I wonder if this could be the more subtle approach? I kept the checkbox for distinguishability and as small as possible above the card. Tho I had to make few pixels room between card rows. Too small checkbox would be behind the corporation tag and it looked very inconvenient in front of it. Colonies and turmoil checkboxes as they were.
> 
> project_cards standard

That would also be terrific.

**Comment by kberg** [comment]
Closing in favor of #5018

**Pull request closed without merging**
